id: 07f1ad121c5445849c8abab1121eb5a8
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN827
  title: སྤྱི་ལོ ༢༠༠༩་ལོར་སྲི་གཅོད་ཀྱིས་ཉར་ཚགས་བྱས་པའི་སྡེ་དགེའི་དམངས་ཁྲོད་ཀྱི་གནའ་དཔེ་བྲིས་མའི་གློག་རྡུལ་འདྲ་བཤུས།
  volumes:
    a335c4fbfb4d4b1795e4a0b3e2d25851:
      image_group_id: I2KG229634
      title: ''
      base_file: v001.txt
  author: ''
